//OpenCV
#include <opencv2/highgui/highgui.hpp>
#include <opencv2/imgproc/imgproc.hpp>
#include <opencv2/video.hpp>

//C++
#include <iostream>

using namespace cv;
using namespace std;

Mat frameOri;
Mat frameGray;
Mat frameBlur;
Mat fgMaskMOG2;//fg mask fg mask generated by MOG2 method
Mat frameCanny;

Ptr<BackgroundSubtractor> pMOG2; //MOG2 Background subtractor
void processVideo();

int main()
{
	namedWindow("frameOri",CV_WINDOW_AUTOSIZE);
        namedWindow("frameMOG",CV_WINDOW_AUTOSIZE);
	namedWindow("frameCanny",CV_WINDOW_AUTOSIZE);

	pMOG2 = createBackgroundSubtractorMOG2(20,16,false);

	processVideo();

        return 0;
}

void processVideo(){
	VideoCapture capture(0);

	while(capture.isOpened()){	

	if(!capture.read(frameOri))
               	break;

	cvtColor(frameOri, frameGray, CV_BGR2GRAY);
        GaussianBlur(frameGray, frameBlur, Size(5,5),1.5);
	pMOG2->apply(frameBlur, fgMaskMOG2);
	Canny(fgMaskMOG2, frameCanny,100,200);

        imshow("frameCanny" ,frameCanny);
	imshow("frameMOG" ,fgMaskMOG2);
	imshow("frameOri" ,frameOri);

	if (waitKey(33) == 27)
        	break;
	}       
}
